---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/datos.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_datos/
      - /bin/rsync -av ./ $DEPLOYPATH